apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-static-website
spec:
  replicas: 2  # Number of container instances
  selector:
    matchLabels:
      app: my-static-website
  template:
    metadata:
      labels:
        app: my-static-website
    spec:
      containers:
        - name: my-static-website
          image: habeebakorede/my-static-web:latest  # Replace with your actual image name
          ports:
            - containerPort: 80

