apiVersion: v1
kind: Service
metadata:
  name: my-static-website-service
spec:
  type: ClusterIP  # Internal service within the cluster
  selector:
    app: my-static-website  # Matches the label in deployment.yaml
  ports:
    - protocol: TCP
      port: 80   # The port exposed by the service
      targetPort: 80  # The port the container is listening on (Nginx)

